// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_Server.Infra.Data.Context;

#nullable disable

namespace SD_Server.Infra.Data.Migrations
{
    [DbContext(typeof(SdServerDbContext))]
    [Migration("20260509164653_AddAvaliationsTable")]
    partial class AddAvaliationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SD_Server.Domain.Features.Avaliations.Avaliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyFatPercentage")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateNextAvaliation")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMC")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentObjective")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalOpinion")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<int>("TypeAvaliation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("StudentId");

                    b.ToTable("tb_Avaliations", (string)null);
                });

            modelBuilder.Entity("SD_Server.Domain.Features.Professionals.Professional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cref")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cref")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tb_Professionals", (string)null);
                });

            modelBuilder.Entity("SD_Server.Domain.Features.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("LastReview")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_Student", (string)null);
                });

            modelBuilder.Entity("SD_Server.Domain.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeAccess")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("tb_Users", (string)null);
                });

            modelBuilder.Entity("SD_Server.Domain.Features.Avaliations.Avaliation", b =>
                {
                    b.HasOne("SD_Server.Domain.Features.Professionals.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SD_Server.Domain.Features.Students.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("SD_Server.Domain.Features.Avaliations.Anamnesis", "Anamnesis", b1 =>
                        {
                            b1.Property<int>("AvaliationId")
                                .HasColumnType("int");

                            b1.Property<int>("ActivityLevel")
                                .HasColumnType("int");

                            b1.Property<bool>("HasInjury")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasMedication")
                                .HasColumnType("bit");

                            b1.Property<string>("InjuryDescription")
                                .HasColumnType("VARCHAR(255)");

                            b1.Property<string>("MedicationDescription")
                                .HasColumnType("VARCHAR(255)");

                            b1.HasKey("AvaliationId");

                            b1.ToTable("tb_Avaliations");

                            b1.WithOwner()
                                .HasForeignKey("AvaliationId");
                        });

                    b.OwnsOne("SD_Server.Domain.Features.Avaliations.BodyComposition", "BodyComposition", b1 =>
                        {
                            b1.Property<int>("AvaliationId")
                                .HasColumnType("int");

                            b1.Property<double?>("Abdomen")
                                .HasColumnType("float");

                            b1.Property<double?>("ArmLeft")
                                .HasColumnType("float");

                            b1.Property<double?>("ArmRight")
                                .HasColumnType("float");

                            b1.Property<double?>("Chest")
                                .HasColumnType("float");

                            b1.Property<double?>("Height")
                                .HasColumnType("float");

                            b1.Property<double?>("Hips")
                                .HasColumnType("float");

                            b1.Property<double?>("LeftThigh")
                                .HasColumnType("float");

                            b1.Property<double?>("RightThigh")
                                .HasColumnType("float");

                            b1.Property<double?>("Waist")
                                .HasColumnType("float");

                            b1.Property<double?>("Weight")
                                .HasColumnType("float");

                            b1.HasKey("AvaliationId");

                            b1.ToTable("tb_Avaliations");

                            b1.WithOwner()
                                .HasForeignKey("AvaliationId");
                        });

                    b.OwnsOne("SD_Server.Domain.Features.Avaliations.Skinfolds", "Skinfolds", b1 =>
                        {
                            b1.Property<int>("AvaliationId")
                                .HasColumnType("int");

                            b1.Property<double?>("Abdominal")
                                .HasColumnType("float");

                            b1.Property<double?>("MidAxillary")
                                .HasColumnType("float");

                            b1.Property<double?>("Pectoral")
                                .HasColumnType("float");

                            b1.Property<double?>("Subscapular")
                                .HasColumnType("float");

                            b1.Property<double?>("Suprailiac")
                                .HasColumnType("float");

                            b1.Property<double?>("Thigh")
                                .HasColumnType("float");

                            b1.Property<double?>("Triceps")
                                .HasColumnType("float");

                            b1.HasKey("AvaliationId");

                            b1.ToTable("tb_Avaliations");

                            b1.WithOwner()
                                .HasForeignKey("AvaliationId");
                        });

                    b.Navigation("Anamnesis");

                    b.Navigation("BodyComposition");

                    b.Navigation("Professional");

                    b.Navigation("Skinfolds");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
